Repository gregnavis/active_record_doctor, pull requests merged in 2025-01, with the labels that each got.

#186 Check timestamp columns (created_at, updated_at) are NOT NULL
  lib/active_record_doctor/detectors/missing_non_null_constraint.rb
  test/active_record_doctor/detectors/missing_non_null_constraint_test.rb
Labels: new feature

#204 missing_foreign_keys: consider column type for foreign key candidates
  lib/active_record_doctor/detectors/missing_foreign_keys.rb
  test/active_record_doctor/detectors/missing_foreign_keys_test.rb
Labels: waiting, false positive

#202 Fix incorrect_dependent_option checker for broken associations
  lib/active_record_doctor/detectors/incorrect_dependent_option.rb
  test/active_record_doctor/detectors/incorrect_dependent_option_test.rb
Labels: bug

#197 Add new checker for tables without default timestamp columns
  README.md
  lib/active_record_doctor.rb
  lib/active_record_doctor/config/default.rb
  lib/active_record_doctor/detectors/table_without_timestamps.rb
  test/active_record_doctor/detectors/table_without_timestamps_test.rb
Labels: new feature

#180 missing_presence_validation: ignore counter cache columns
  lib/active_record_doctor/detectors/missing_presence_validation.rb
  test/active_record_doctor/detectors/missing_presence_validation_test.rb
Labels: false positive

#201 missing_non_null_constraint: ignore database views
  active_record_doctor.gemspec
  lib/active_record_doctor/detectors/missing_non_null_constraint.rb
  test/active_record_doctor/detectors/missing_non_null_constraint_test.rb
Labels: waiting, false positive

#206 unindexed_foreign_keys: consider column type for foreign key candidates
  lib/active_record_doctor/detectors/base.rb
  lib/active_record_doctor/detectors/missing_foreign_keys.rb
  lib/active_record_doctor/detectors/unindexed_foreign_keys.rb
  test/active_record_doctor/detectors/unindexed_foreign_keys_test.rb
Labels: waiting, false positive
